# Generated by Django 5.2.5 on 2025-08-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='vehicle_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='registration_number',
            new_name='vehicle_number',
        ),
    ]
