# Generated by Django 5.2.5 on 2025-08-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_name_vehicle_vehicle_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('document', models.ImageField(upload_to='kyc/')),
                ('dob', models.DateField()),
                ('kyc_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_approved', models.BooleanField(default=False)),
                ('kyc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_forms', to='accounts.vehicle')),
            ],
        ),
    ]
